if(NOT FTE_PLUGIN_ODE)
	return()
endif()

fte_add_plugin(ode
	TITLE "ODE Physics"
	DESCRIPTION "Provides Rigid Body Physics behaviours."
	CATEGORY "Plugins"
	SOURCES
		${FTE_ENGINE_COMMON_DIR}/com_phys_ode.c
		${FTE_ENGINE_COMMON_DIR}/mathlib.c
		${FTE_PLUGINS_ROOT_DIR}/plugin.c
	INCLUDE_DIRECTORIES
		${FTE_PLUGINS_ROOT_DIR}
		${FTE_ENGINE_COMMON_DIR}
		${FTE_ENGINE_CLIENT_DIR}
		${FTE_ENGINE_QCLIB_DIR}
		${FTE_ENGINE_GL_DIR}
	COMPILE_DEFINITIONS
		ODE_STATIC
	DEPENDENCIES
		ODE
)
