if(NOT FTE_PLUGIN_ROTT)
	return()
endif()

fte_add_plugin(rott
	TITLE "Rott Plugin"
	DESCRIPTION "Support for Rise of the Triad formats."
	CATEGORY "Plugins"
	SOURCES
		${FTE_PLUGINS_ROOT_DIR}/rott/fs_rott.c
		${FTE_PLUGINS_ROOT_DIR}/rott/mod_rott.c
		${FTE_PLUGINS_ROOT_DIR}/rott/rott.c
		${FTE_PLUGINS_ROOT_DIR}/plugin.c
	INCLUDE_DIRECTORIES
		${FTE_PLUGINS_ROOT_DIR}
		${FTE_PLUGINS_ROOT_DIR}/rott
		${FTE_ENGINE_CLIENT_DIR}
		${FTE_ENGINE_QCLIB_DIR}
		${FTE_ENGINE_GL_DIR}
		${FTE_ENGINE_COMMON_DIR}
	DEPENDENCIES
		$<TARGET_NAME_IF_EXISTS:Math::Math>
	COMPILE_DEFINITIONS
		MULTITHREAD
)
